apiVersion: v1
kind: Service
metadata:
  name: cloudcore
  namespace: kubeedge
  labels:
    k8s-app: kubeedge
    kubeedge: cloudcore
spec:
  ports:
  - port: 10000
    name: cloudhub
  - port: 10002
    name: cloudhub-2
  selector:
    k8s-app: kubeedge
    kubeedge: cloudcore
  type: NodePort
