apiVersion: v1
kind: Service
metadata:
  name: cloudcore-lb
  namespace: kubeedge
  labels:
    k8s-app: kubeedge
    kubeedge: cloudcore
spec:
  type: LoadBalancer
  selector:
    k8s-app: kubeedge
    kubeedge: cloudcore
  ports:
  - protocol: TCP
    port: 10000
    targetPort: 10000
    name: cloudhub
  - protocol: TCP
    port: 10002
    targetPort: 10002
    name: cloudhub-2
