apiVersion: v1
data:
  serverConf.conf: |
    include /etc/nginx/customization.d/rate-limit-usage.conf;
    include /etc/nginx/customization.d/auth-usage.conf;
    include /etc/nginx/customization.d/auth-location.conf;
    include /etc/nginx/customization.d/server-extension.conf;
    include /etc/nginx/customization.d/default-error-page.conf;

    set $isbackoffice "";

    location / {
      include /etc/nginx/customization.d/header-debug.conf;
      include /etc/nginx/customization.d/auth-set-userid.conf;
      include /etc/nginx/set_proxy_headers.conf;
      include /etc/nginx/customization.d/root-location-extension.conf;

      proxy_pass http://$proxy_name$proxy_url;
    }
kind: ConfigMap
metadata:
  name: api-gateway-platform
  labels:
    app.kubernetes.io/part-of: edge-computing
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: '{{STAGE_TO_DEPLOY}}'
    mia-platform.eu/tenant: polimi
