apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-portal
  annotations:
    mia-platform.eu/deployment-date: '{{RELEASE_DATE}}'
    mia-platform.eu/commit-author: '{{AUTHOR_EMAIL}}'
    mia-platform.eu/commit-sha: '{{COMMIT_SHA}}'
    mia-platform.eu/version: 8.4.1
    fluentbit.io/parser: nginx
  labels:
    app: api-portal
    app.kubernetes.io/name: api-portal
    app.kubernetes.io/version: 1.13.7
    app.kubernetes.io/component: custom
    app.kubernetes.io/part-of: edge-computing
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: '{{STAGE_TO_DEPLOY}}'
    mia-platform.eu/tenant: polimi
    mia-platform.eu/log-type: mia-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-portal
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 1
  template:
    metadata:
      annotations:
        fluentbit.io/parser: nginx
      labels:
        app: api-portal
        app.kubernetes.io/name: api-portal
        app.kubernetes.io/version: 1.13.7
        app.kubernetes.io/component: custom
        app.kubernetes.io/part-of: edge-computing
        app.kubernetes.io/managed-by: mia-platform
        mia-platform.eu/stage: '{{STAGE_TO_DEPLOY}}'
        mia-platform.eu/tenant: polimi
        mia-platform.eu/log-type: mia-nginx
    spec:
      imagePullSecrets:
        - name: nexus-gcloud
      terminationGracePeriodSeconds: 30
      containers:
        - name: api-portal
          image: nexus.mia-platform.eu/api-portal/website:1.13.7
          imagePullPolicy: Always
          volumeMounts: []
          args: []
          env:
            - name: HTTP_PORT
              value: '8080'
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              port: 8080
              path: /index.html
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 20
            httpGet:
              port: 8080
              path: /index.html
      volumes: []
