apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-service
  annotations:
    mia-platform.eu/deployment-date: '{{RELEASE_DATE}}'
    mia-platform.eu/commit-author: '{{AUTHOR_EMAIL}}'
    mia-platform.eu/commit-sha: '{{COMMIT_SHA}}'
    mia-platform.eu/version: 8.4.1
    fluentbit.io/parser: pino
  labels:
    app: authorization-service
    app.kubernetes.io/name: authorization-service
    app.kubernetes.io/version: 2.0.2
    app.kubernetes.io/component: custom
    app.kubernetes.io/part-of: edge-computing
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: '{{STAGE_TO_DEPLOY}}'
    mia-platform.eu/tenant: polimi
    mia-platform.eu/log-type: mia-json
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization-service
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 1
  template:
    metadata:
      annotations:
        fluentbit.io/parser: pino
      labels:
        app: authorization-service
        app.kubernetes.io/name: authorization-service
        app.kubernetes.io/version: 2.0.2
        app.kubernetes.io/component: custom
        app.kubernetes.io/part-of: edge-computing
        app.kubernetes.io/managed-by: mia-platform
        mia-platform.eu/stage: '{{STAGE_TO_DEPLOY}}'
        mia-platform.eu/tenant: polimi
        mia-platform.eu/log-type: mia-json
    spec:
      imagePullSecrets:
        - name: nexus-gcloud
      containers:
        - name: authorization-service
          image: nexus.mia-platform.eu/core/authorization-service:2.0.2
          imagePullPolicy: Always
          volumeMounts:
            - name: authorization-service-config
              mountPath: /configs
              readOnly: true
          args: []
          env:
            - name: LOG_LEVEL
              value: '{{LOG_LEVEL}}'
            - name: HTTP_PORT
              value: '3000'
            - name: CONFIGURATION_PATH
              value: /configs
            - name: CONFIGURATION_FILE_NAME
              value: auth
            - name: BACKOFFICE_HEADER_KEY
              value: isbackoffice
            - name: SERVICE_VERSION
              value: 2.0.2
            - name: USERINFO_URL
              value: http://auth0-client/userinfo
            - name: CUSTOM_USER_ID_KEY
              value: sub
            - name: HEADERS_TO_PROXY
              value: x-request-id,request-id,cookie,authorization,client-type,host,x-forwarded-host
            - name: AUTHORIZATION_STRICT_MODE_ENABLED
              value: 'true'
            - name: USER_PROPERTIES_TO_PROXY
              value: ''
            - name: CLIENT_TYPE_HEADER_KEY
              value: client-type
            - name: BACKOFFICE_USERINFO_URL
              value: ''
            - name: CUSTOM_PERMISSIONS_KEY
              value: permissions
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              port: 3000
              path: /-/ready
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 20
            httpGet:
              port: 3000
              path: /-/healthz
      volumes:
        - name: authorization-service-config
          configMap:
            name: authorization-service-config
