apiVersion: v1
kind: Service
metadata:
  name: auth0-client
  annotations:
    mia-platform.eu/deployment-date: '{{RELEASE_DATE}}'
    mia-platform.eu/commit-author: '{{AUTHOR_EMAIL}}'
    mia-platform.eu/commit-sha: '{{COMMIT_SHA}}'
    mia-platform.eu/version: 8.5.0
  labels:
    app: auth0-client
    app.kubernetes.io/name: auth0-client
    app.kubernetes.io/version: 3.2.2
    app.kubernetes.io/component: custom
    app.kubernetes.io/part-of: edge-computing
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: '{{STAGE_TO_DEPLOY}}'
    mia-platform.eu/tenant: polimi
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: null
  selector:
    app: auth0-client
