apiVersion: v1
data:
  config.json: |-
    {
      "clients": {
        "api": {
          "auth0Url": "{{AUTH0_TENANT_URL}}",
          "clientId": "{{AUTH0_API_CLIENT_ID}}",
          "clientSecret": "{{AUTH0_API_CLIENT_SECRET}}",
          "redirectUrl": "{{AUTH0_REDIRECT_URL}}",
          "supportedConnections": [
            "{{AUTH0_CONNECTION}}"
          ],
          "defaultConnection": "{{AUTH0_CONNECTION}}",
          "scopes": [
            "offline_access",
            "profile"
          ]
        }
      },
      "managementClient": {
        "auth0Url": "{{AUTH0_TENANT_URL}}",
        "clientId": "{{AUTH0_MANAGEMENT_CLIENT_ID}}",
        "clientSecret": "{{AUTH0_MANAGEMENT_CLIENT_SECRET}}",
        "supportedConnections": [
          "{{AUTH0_CONNECTION}}"
        ],
        "defaultCreateUserConnection": "{{AUTH0_CONNECTION}}"
      },
      "customClaimsNamespaces": [
        "https://edge-computing.polimi-ecb7249.gcp.mia-platform.eu/app_metadata",
        "https://edge-computing.polimi-ecb7249.gcp.mia-platform.eu/user_metadata"
      ]
    }
kind: ConfigMap
metadata:
  name: auth0-client-config
  labels:
    app.kubernetes.io/part-of: edge-computing
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: '{{STAGE_TO_DEPLOY}}'
    mia-platform.eu/tenant: polimi
