apiVersion: v1
data:
  mongo.url.short: '{{MONGODB_SHORT_URL}}'
  mongo.url: '{{MONGODB_URL}}'
  redis.url: '{{REDIS_URL}}'
  redis.host: '{{REDIS_HOST}}'
kind: ConfigMap
metadata:
  name: db-config
  labels:
    app.kubernetes.io/part-of: edge-computing
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: '{{STAGE_TO_DEPLOY}}'
    mia-platform.eu/tenant: polimi
