apiVersion: v1
kind: Service
metadata:
  name: export-service
  annotations:
    mia-platform.eu/deployment-date: '{{RELEASE_DATE}}'
    mia-platform.eu/commit-author: '{{AUTHOR_EMAIL}}'
    mia-platform.eu/commit-sha: '{{COMMIT_SHA}}'
    mia-platform.eu/version: 8.5.0
  labels:
    app: export-service
    app.kubernetes.io/name: export-service
    app.kubernetes.io/component: core
    app.kubernetes.io/part-of: edge-computing
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: '{{STAGE_TO_DEPLOY}}'
    mia-platform.eu/tenant: polimi
spec:
  type: ExternalName
  externalName: export-service.multitenant.svc.cluster.local
  selector: {}
