apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-gateway
  annotations:
    mia-platform.eu/deployment-date: '{{RELEASE_DATE}}'
    mia-platform.eu/commit-author: '{{AUTHOR_EMAIL}}'
    mia-platform.eu/commit-sha: '{{COMMIT_SHA}}'
    mia-platform.eu/version: 8.4.1
    fluentbit.io/parser: pino
  labels:
    app: microservice-gateway
    app.kubernetes.io/name: microservice-gateway
    app.kubernetes.io/version: 6.0.5
    app.kubernetes.io/component: custom
    app.kubernetes.io/part-of: edge-computing
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: '{{STAGE_TO_DEPLOY}}'
    mia-platform.eu/tenant: polimi
    mia-platform.eu/log-type: mia-json
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-gateway
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 1
  template:
    metadata:
      annotations:
        fluentbit.io/parser: pino
      labels:
        app: microservice-gateway
        app.kubernetes.io/name: microservice-gateway
        app.kubernetes.io/version: 6.0.5
        app.kubernetes.io/component: custom
        app.kubernetes.io/part-of: edge-computing
        app.kubernetes.io/managed-by: mia-platform
        mia-platform.eu/stage: '{{STAGE_TO_DEPLOY}}'
        mia-platform.eu/tenant: polimi
        mia-platform.eu/log-type: mia-json
    spec:
      imagePullSecrets:
        - name: nexus-gcloud
      containers:
        - name: microservice-gateway
          image: nexus.mia-platform.eu/core/microservice-gateway:6.0.5
          imagePullPolicy: Always
          volumeMounts:
            - name: microservice-gateway-config
              mountPath: /home/node/app/configs
              readOnly: true
          args: []
          env:
            - name: CONFIGURATION_PATH
              value: /home/node/app/configs/config.json
            - name: LOG_LEVEL
              value: '{{LOG_LEVEL}}'
            - name: HTTP_PORT
              value: '3000'
            - name: SERVICE_PREFIX
              value: /
            - name: TRUSTED_PROXIES
              value: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
            - name: DISABLE_STRICT_CONTENT_TYPE_CHECK
              value: 'false'
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              port: 3000
              path: /-/ready
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 20
            httpGet:
              port: 3000
              path: /-/healthz
      volumes:
        - name: microservice-gateway-config
          configMap:
            name: microservice-gateway-config
