apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-service
  annotations:
    mia-platform.eu/deployment-date: '{{RELEASE_DATE}}'
    mia-platform.eu/commit-author: '{{AUTHOR_EMAIL}}'
    mia-platform.eu/commit-sha: '{{COMMIT_SHA}}'
    mia-platform.eu/version: 8.4.1
    fluentbit.io/parser: pino
  labels:
    app: streaming-service
    app.kubernetes.io/name: streaming-service
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: custom
    app.kubernetes.io/part-of: edge-computing
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: '{{STAGE_TO_DEPLOY}}'
    mia-platform.eu/tenant: polimi
    mia-platform.eu/log-type: mia-json
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-service
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 1
  template:
    metadata:
      annotations:
        fluentbit.io/parser: pino
      labels:
        app: streaming-service
        app.kubernetes.io/name: streaming-service
        app.kubernetes.io/version: latest
        app.kubernetes.io/component: custom
        app.kubernetes.io/part-of: edge-computing
        app.kubernetes.io/managed-by: mia-platform
        mia-platform.eu/stage: '{{STAGE_TO_DEPLOY}}'
        mia-platform.eu/tenant: polimi
        mia-platform.eu/log-type: mia-json
    spec:
      imagePullSecrets:
        - name: nexus-gcloud
      terminationGracePeriodSeconds: 30
      containers:
        - name: streaming-service
          image: nexus.mia-platform.eu/edge-computing/streaming-service
          imagePullPolicy: Always
          volumeMounts: []
          args: []
          env:
            - name: LOG_LEVEL
              value: '{{LOG_LEVEL}}'
            - name: MICROSERVICE_GATEWAY_SERVICE_NAME
              value: microservice-gateway
            - name: TRUSTED_PROXIES
              value: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
            - name: HTTP_PORT
              value: '3000'
            - name: USERID_HEADER_KEY
              value: miauserid
            - name: GROUPS_HEADER_KEY
              value: miausergroups
            - name: CLIENTTYPE_HEADER_KEY
              value: client-type
            - name: BACKOFFICE_HEADER_KEY
              value: isbackoffice
            - name: USER_PROPERTIES_HEADER_KEY
              value: miauserproperties
            - name: MONGODB_URL
              value: '{{MONGODB_SHORT_URL}}'
            - name: AUTH0_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: auth0-secret
                  key: AUTH0_ACCESS_TOKEN
            - name: AUTH0_API_URL
              value: https://polimi-edge-computing.eu.auth0.com
            - name: AUDIENCE
              value: https://polimi-edge-computing.eu.auth0.com/api/v2/
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth0-secret
                  key: CLIENT_SECRET
            - name: CLIENT_ID
              value: tEydfVBObitQV0a048IAMuip1iQXPmTO
            - name: API_SERVICE_HOST
              value: http://localhost:8888
            - name: STREAMKEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth0-secret
                  key: STREAMKEY_SECRET
            - name: EDGENODE_SECRET
              value: NeverGonnaGiveYouUp
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              port: 3000
              path: /-/ready
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 1
            failureThreshold: 3
            httpGet:
              port: 3000
              path: /-/healthz
      volumes: []
